"""empty message

Revision ID: c4ecdd17257a
Revises: f0b0182ededf
Create Date: 2020-06-04 18:11:28.258145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ecdd17257a'
down_revision = 'f0b0182ededf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'todos', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='unique')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
